import {
  solveBorderAlpha,
  solveForegroundLightness,
  solveForegroundSpec,
} from "./math.ts";
import type {
  BorderTargets,
  ColorSpec,
  Mode,
  PaletteConfig,
  SolverConfig,
  SurfaceGroup,
} from "./types.ts";

export function toHighContrast(config: SolverConfig): SolverConfig {
  return {
    ...config,
    anchors: {
      ...config.anchors,
      keyColors: {}, // Force grayscale
      page: {
        ...config.anchors.page,
        light: {
          ...config.anchors.page.light,
          start: { background: 1.0, adjustable: false },
          end: { background: 0.0, adjustable: false },
        },
        dark: {
          ...config.anchors.page.dark,
          start: { background: 0.0, adjustable: false },
          end: { background: 1.0, adjustable: false },
        },
      },
      inverted: {
        ...config.anchors.inverted,
        light: {
          ...config.anchors.inverted.light,
          start: { background: 0.0, adjustable: false },
          end: { background: 1.0, adjustable: false },
        },
        dark: {
          ...config.anchors.inverted.dark,
          start: { background: 1.0, adjustable: false },
          end: { background: 0.0, adjustable: false },
        },
      },
    },
  };
}

export function generateTokensCss(
  groups: SurfaceGroup[],
  backgrounds: Map<string, Record<Mode, ColorSpec>>,
  borderTargets?: BorderTargets,
  selector?: string,
  palette?: PaletteConfig
): string {
  const rootLines: string[] = [];
  const propertyLines: string[] = [];

  rootLines.push("/* AUTO-GENERATED by src/lib/generator.ts */");

  // Note: We assume @property definitions are loaded via engine.css
  // Re-declaring them here causes transition glitches in some browsers
  // when the stylesheet is updated dynamically.

  const toNumber = (n: number): number => parseFloat(n.toFixed(4));

  // --- Primitives (Shadows & Focus) ---
  const rootSelector = selector || ":root";
  rootLines.push(`${rootSelector} {`);

  // Shadows
  rootLines.push(`  /* Elevation */`);
  // In Dark Mode, black shadows are often invisible on dark backgrounds.
  // We use a white "glow" (diffuse light) to simulate elevation.
  rootLines.push(
    `  --shadow-sm: 0 1px 2px 0 light-dark(oklch(0 0 0 / 0.05), oklch(1 0 0 / 0.15));`
  );

  rootLines.push(`  --shadow-md: 
    0 4px 6px -1px light-dark(oklch(0 0 0 / 0.1), oklch(1 0 0 / 0.15)), 
    0 2px 4px -1px light-dark(oklch(0 0 0 / 0.06), oklch(1 0 0 / 0.1));`);

  rootLines.push(`  --shadow-lg: 
    0 10px 15px -3px light-dark(oklch(0 0 0 / 0.1), oklch(1 0 0 / 0.15)), 
    0 4px 6px -2px light-dark(oklch(0 0 0 / 0.05), oklch(1 0 0 / 0.1));`);

  rootLines.push(`  --shadow-xl: 
    0 20px 25px -5px light-dark(oklch(0 0 0 / 0.1), oklch(1 0 0 / 0.15)), 
    0 10px 10px -5px light-dark(oklch(0 0 0 / 0.04), oklch(1 0 0 / 0.1));`);

  // Focus
  rootLines.push(`  /* Focus */`);
  rootLines.push(`  --focus-ring-color: light-dark(
    oklch(0.45 0.2 var(--hue-brand, 250)),
    oklch(0.75 0.2 var(--hue-brand, 250))
  );`);

  // Data Visualization Palette
  if (palette && palette.hues) {
    rootLines.push(`  /* Data Visualization */`);
    const targetChroma = palette.targetChroma ?? 0.12;
    const targetContrast = palette.targetContrast ?? 60;

    // We need to solve for lightness against the page background.
    // Since we don't have the full config here, we rely on the 'page' surface being present in the map.
    const pageBg = backgrounds.get("page") ?? {
      light: { l: 1, c: 0, h: 0 },
      dark: { l: 0, c: 0, h: 0 },
    };

    palette.hues.forEach((hue, index) => {
      // Solve for Light Mode
      const lightL = solveForegroundLightness(pageBg.light.l, targetContrast);

      // Solve for Dark Mode
      const darkL = solveForegroundLightness(pageBg.dark.l, targetContrast);

      rootLines.push(
        `  --chart-${index + 1}: light-dark(
    oklch(${toNumber(lightL)} ${toNumber(targetChroma)} ${toNumber(hue)}),
    oklch(${toNumber(darkL)} ${toNumber(targetChroma)} ${toNumber(hue)})
  );`
      );
    });
  }

  rootLines.push(`}`);
  rootLines.push("");

  for (const group of groups) {
    for (const surface of group.surfaces) {
      const bgLight = backgrounds.get(surface.slug)?.light ?? {
        l: 0,
        c: 0,
        h: 0,
      };
      const bgDark = backgrounds.get(surface.slug)?.dark ?? {
        l: 0,
        c: 0,
        h: 0,
      };

      const lightSpec = solveForegroundSpec(bgLight.l);
      const darkSpec = solveForegroundSpec(bgDark.l);

      // Hue shift is already applied in solve()

      // Generate the Class Definition
      const prefix = selector ? `${selector} ` : "";
      let classSelector = `.surface-${surface.slug}`;

      // Special case: Apply 'page' surface tokens to body
      if (surface.slug === "page") {
        classSelector += ", body";
      }

      rootLines.push(`${prefix}${classSelector} {`);

      // 1. Surface Token
      rootLines.push(
        `  --surface-token: light-dark(
    oklch(${toNumber(bgLight.l)} ${toNumber(bgLight.c)} ${toNumber(bgLight.h)}),
    oklch(${toNumber(bgDark.l)} ${toNumber(bgDark.c)} ${toNumber(bgDark.h)})
  );`
      );

      // 2. Text Tokens
      rootLines.push(
        `  --text-high-token: light-dark(
    oklch(${toNumber(lightSpec["fg-high"])} 0 0),
    oklch(${toNumber(darkSpec["fg-high"])} 0 0)
  );`
      );

      rootLines.push(
        `  --text-subtle-token: light-dark(
    oklch(${toNumber(lightSpec["fg-subtle"])} 0 0),
    oklch(${toNumber(darkSpec["fg-subtle"])} 0 0)
  );`
      );

      rootLines.push(
        `  --text-subtlest-token: light-dark(
    oklch(${toNumber(lightSpec["fg-subtlest"])} 0 0),
    oklch(${toNumber(darkSpec["fg-subtlest"])} 0 0)
  );`
      );

      // 3. Border Tokens
      if (borderTargets) {
        const solveBorder = (
          bgL: number,
          textL: number,
          target: number
        ): number => solveBorderAlpha(bgL, textL, target);

        const lightDec = solveBorder(
          bgLight.l,
          lightSpec["fg-strong"],
          borderTargets.decorative
        );
        const darkDec = solveBorder(
          bgDark.l,
          darkSpec["fg-strong"],
          borderTargets.decorative
        );
        const lightInt = solveBorder(
          bgLight.l,
          lightSpec["fg-strong"],
          borderTargets.interactive
        );
        const darkInt = solveBorder(
          bgDark.l,
          darkSpec["fg-strong"],
          borderTargets.interactive
        );

        const lightBorderL = lightSpec["fg-strong"];
        const darkBorderL = darkSpec["fg-strong"];

        rootLines.push(
          `  --border-dec-token: light-dark(
    oklch(${toNumber(lightBorderL)} 0 0 / ${toNumber(lightDec)}),
    oklch(${toNumber(darkBorderL)} 0 0 / ${toNumber(darkDec)})
  );`
        );

        rootLines.push(
          `  --border-int-token: light-dark(
    oklch(${toNumber(lightBorderL)} 0 0 / ${toNumber(lightInt)}),
    oklch(${toNumber(darkBorderL)} 0 0 / ${toNumber(darkInt)})
  );`
        );
      }

      rootLines.push(`}`); // End class

      // States (Hover/Active)
      if (surface.states) {
        surface.states.forEach((state) => {
          const stateSlug = `${surface.slug}-${state.name}`;
          const bgState = backgrounds.get(stateSlug);

          if (bgState) {
            // We generate a modifier class? Or pseudo-class?
            // The config says "states: [{name: 'hover'}]".
            // Usually this maps to `.surface-card:hover`.
            // But sometimes it might be a class `.surface-card-selected`.
            // Let's assume pseudo-classes for standard names, and classes for others?
            // The original code generated `--surface-card-hover-token`.
            // And `utilities.css` mapped `.surface-card:hover` to that token.

            // Here we can generate:
            // .surface-card:hover { --surface-token: ... }

            const stateSelector =
              state.name === "hover" || state.name === "active"
                ? `.surface-${surface.slug}:${state.name}`
                : `.surface-${surface.slug}-${state.name}`; // e.g. .surface-card-selected

            rootLines.push(`${prefix}${stateSelector} {`);
            rootLines.push(
              `  --surface-token: light-dark(
    oklch(${toNumber(bgState.light.l)} ${toNumber(bgState.light.c)} ${toNumber(
                bgState.light.h
              )}),
    oklch(${toNumber(bgState.dark.l)} ${toNumber(bgState.dark.c)} ${toNumber(
                bgState.dark.h
              )})
  );`
            );
            rootLines.push(`}`);
          }
        });
      }
      rootLines.push("");
    }
  }

  return [...propertyLines, "", ...rootLines].join("\n");
}
