import * as ts from "typescript";
import { describe, expect, it } from "vitest";
import type { Theme } from "../../types.ts";
import { toTypeScriptMetadata } from "../metadata.ts";

describe("toTypeScriptMetadata", () => {
  it("exports a stable, valid TypeScript module", () => {
    const mockTheme = {
      surfaces: [
        { slug: "page", polarity: "page" },
        { slug: "action", polarity: "inverted" },
        { slug: "spotlight", polarity: "inverted" },
      ],
    } as unknown as Theme;

    const output = toTypeScriptMetadata(mockTheme, {
      source: "color-config.json",
    });

    expect(output).toBe(
      [
        "/**",
        " * Auto-generated by @axiomatic-design/color",
        " * Source: color-config.json",
        " * @generated",
        " */",
        "",
        "/** Selectors for surfaces with inverted polarity */",
        "export const invertedSelectors = [",
        '  ".surface-action",',
        '  ".surface-spotlight",',
        "] as const;",
        "",
        "/** Default tau for the initial theme state (1 = light). */",
        "export const defaultTau = 1 as const;",
        "",
      ].join("\n"),
    );

    const transpile = ts.transpileModule(output, {
      compilerOptions: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.ESNext,
      },
    });
    expect(transpile.diagnostics?.length ?? 0).toBe(0);
  });

  it("handles no inverted surfaces", () => {
    const mockTheme = {
      surfaces: [{ slug: "page", polarity: "page" }],
    } as unknown as Theme;

    const output = toTypeScriptMetadata(mockTheme);

    expect(output).toContain("export const invertedSelectors = [");
    expect(output).toContain("] as const");
    expect(output).not.toContain(".surface-page");
  });

  it("omits the source line when not provided", () => {
    const mockTheme = { surfaces: [] } as unknown as Theme;
    const output = toTypeScriptMetadata(mockTheme);
    expect(output).not.toContain("Source:");
  });

  it("includes @generated marker", () => {
    const mockTheme = { surfaces: [] } as unknown as Theme;
    const output = toTypeScriptMetadata(mockTheme);
    expect(output).toContain("@generated");
  });
});
