import type { Theme } from "../types.ts";

/**
 * Generates TypeScript metadata file content from a solved theme.
 */
export function toTypeScriptMetadata(
  theme: Theme,
  options?: { source?: string },
): string {
  const lines: string[] = [];

  // Header
  lines.push(`/**`);
  lines.push(` * Auto-generated by @axiomatic-design/color`);
  if (options?.source) {
    lines.push(` * Source: ${options.source}`);
  }
  lines.push(` * @generated`);
  lines.push(` */`);
  lines.push(``);

  // Extract inverted selectors from surfaces with polarity === "inverted"
  const invertedSurfaces = theme.surfaces
    .filter((s) => s.polarity === "inverted")
    .map((s) => `.surface-${s.slug}`);

  lines.push(`/** Selectors for surfaces with inverted polarity */`);
  lines.push(`export const invertedSelectors = [`);
  for (const selector of invertedSurfaces) {
    lines.push(`  "${selector}",`);
  }
  lines.push(`] as const;`);
  lines.push(``);

  // Default tau - runtime defaults to 1 unless the consumer overrides it.
  lines.push(`/** Default tau for the initial theme state (1 = light). */`);
  lines.push(`export const defaultTau = 1 as const;`);
  lines.push(``);

  return lines.join("\n");
}
