import type { Theme } from "../types.ts";

/**
 * Generates TypeScript metadata file content from a solved theme.
 */
export function generateMetadata(theme: Theme): string {
  const lines: string[] = [];

  // Header
  lines.push(`/**`);
  lines.push(` * Auto-generated by @axiomatic-design/color`);
  lines.push(` * @generated`);
  lines.push(` */`);
  lines.push(``);

  // Extract inverted selectors from surfaces with polarity === "inverted"
  const invertedSurfaces = theme.surfaces
    .filter((s) => s.polarity === "inverted")
    .map((s) => `.surface-${s.slug}`);

  lines.push(`/** Selectors for surfaces with inverted polarity */`);
  lines.push(`export const invertedSelectors = [`);
  for (const selector of invertedSurfaces) {
    lines.push(`  "${selector}",`);
  }
  lines.push(`] as const;`);
  lines.push(``);

  // Default tau - always 1 for light mode default
  lines.push(
    `/** The theme polarity (-1 for dark default, 1 for light default) */`,
  );
  lines.push(`export const defaultTau = 1;`);
  lines.push(``);

  return lines.join("\n");
}
