/**
 * Auto-generated by @axiomatic-design/color
 * Source: ../color-config.json
 * @generated
 */

/** Selectors for surfaces with inverted polarity */
export const invertedSelectors = [
  ".surface-action",
  ".surface-spotlight",
] as const;

/** Default tau for the initial theme state (1 = light). */
export const defaultTau = 1 as const;
